---
  - name: Install dependencias
    ansible.builtin.apt:
      pkg: 
      - mysql-server 
      - python3-pymysql
      state: latest
      update_cache: yes
    become: yes
  - name: Criando uma tabela no BD
    community.mysql.mysql_db:
      name: '{{wp_db_name}}'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes
  - name: Cria um usuário, sua senha e os privilégios 
    community.mysql.mysql_user:
      name: '{{wp_db_user}}'
      password: '{{wp_db_passw}}'
      priv: '{{wp_db_name}}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
      host: "{{ item }}"
    with_items:
    - "localhost"
    - "127.0.0.1"
    - "{{wp_ip}}"
    become: yes
  - name: Configuraçãp do banco de dados para permitir acesso
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
    become: yes
    notify:
     - restart mysql